name: Get-Contest-List
on: [push]
  # workflow_dispatch:
  # schedule:
  #   # IMPORTANT: Set cron job in UTC timezone
  #   - cron:  '0 12 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - run: pip install requests
      - run: pip install bs4
      - run: pip install BeautifulSoup4
      - run: pip install chardet
      - run: python src/basgc.py
      
